LIBS += \
    apps/$(APP)/ubasic.$(OBJEXT) \
    apps/$(APP)/tokenizer.$(OBJEXT)

CONS_ENABLED=Y
CONS_RX_ENABLED=Y
SHELL_ENABLED=Y
SHELL_RAW_ENABLED=Y
LED_P2_3_ENABLED=Y
MAC_ENABLED=Y
SLEEP_ENABLED=Y
ITOA_ENABLED=Y
WATCHDOG_ENABLED=Y
CRYPTO_ENABLED=Y

