LIBS += apps/$(APP)/json.$(OBJEXT) apps/$(APP)/line.$(OBJEXT)

TX_HIGHPOWER_ENABLED=Y
CONS_ENABLED=Y
CONS_TX_MINIMAL_ENABLED=Y
CONS_RX_ENABLED=Y
CONS_RX_MINIMAL_ENABLED=Y
NET_ENABLED=Y
NET_TCP_ENABLED=Y
LED_P2_3_ENABLED=Y
COORDINATOR_ENABLED=Y
MAC_ENABLED=Y
WATCHDOG_ENABLED=Y
SPI_ENABLED=Y

CRYPTO_ENABLED=Y

